### PR TITLE
Use nokogiri to only autolink text elements. Resolves #77

### LINKED ISSUE #77: External link href's broken
```ruby
irb(main):006:0> WikiCloth::Parser.new(:data => "[https://github.com/repo/README.md README]").to_html
=> "\n<p><a href=\"<a href=\"https://github.com/repo/README.md\" rel=\"nofollow\">https://github.com/repo/README.md</a>\" target=\"_blank\">README</a></p>"
irb(main):007:0> WikiCloth::VERSION
=> "0.8.2"
```

### PR DESCRIPTION
**Pull request by dometto**
Issue #77 is caused by auto_linking with `Twitter::Autolink`, which is not sensitive to html `<a>` tags. So it would autolink the `href` attribute of exisiting links. This PR resolves the problem by using nokogiri to parse the string to be autolinked, and apply autolinking only to `Nokogiri::Text` nodes.

### CODE REVIEW

**Comment by dometto** [comment]
Note that I didn't manage to get the tests running locally, and although they pass on Travis, I'm not sure the tests are actually running there, either. What should I do to run the tests? `bundle exec rake` just gives me:

```
$ bundle exec rake
~/.rvm/rubies/ruby-2.0.0-p0/bin/ruby -I"lib" -I"~/.rvm/gems/ruby-2.0.0-p0/gems/rake-10.4.2/lib" "~/.rvm/gems/ruby-2.0.0-p0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/*_test.rb" 
$
```

**Comment by nricciar** [comment]
I think the tests may be broken currently.. Not sure exactly when they
stopped working, but I think a ruby update broke them.  I will look into
getting them working again shortly hopefully.

--
David

**Comment by dometto** [comment]
I reactivated the tests; there was little use in making a separate PR out of them because the tests would fail anyway. So I edited some tests to account for trivial changes in the generated HTML (mostly newlines), and slightly changed the autolinking implementation. Since Nokogiri was changing html entities like `&lt;` back into `<`, the sanitization test was failing. I had to hack in the gsub to account for this.

**Comment by dometto** [comment]
The tests are actually executing and passing locally; no idea why they aren't running on travis.

**Comment by dometto** [comment]
Ah, spoke too soon -- they are running and passing on travis, too. :)

**Comment by bartkamphorst** [comment]
@nricciar apologies for introducing issue https://github.com/nricciar/wikicloth/issues/77 . @dometto Thanks for resolving the issue so quickly!

File: lib/wikicloth/core_ext.rb [hunk 1]
```diff
@@ -34,7 +36,13 @@ def auto_link
     end
   else
     def auto_link
-      Twitter::Autolink.auto_link(to_s)
+      doc = Nokogiri::HTML::DocumentFragment.parse(to_s)
```
Comment (dometto) [inline lib/wikicloth/core_ext.rb]: We might consider doing:
```ruby
next if node.parent.name == 'a'
```
...so that URL's within `<a>` tags won't be autolinked.

**Comment by bartkamphorst** [comment]
\o/ Thanks @nricciar !

**Comment by dometto** [comment]
Thanks! Note that the current latest version of the gem is seriously broken by default, so you might want to yank that version and build a new one.

Would appreciate a ping when you release a new gem, I'll see about getting `github/markup` to use it then!

**Comment by dometto** [comment]
@nricciar, I still think a new gem release would be in order due to the severity of the bug this fixed. Sorry to bother you again. :)

**Comment by nricciar** [comment]
No worries.  I tried to push a new version this morning, but it was being rejected as invalid for some reason.. dunno if this is server side or something I did yet as I didnt have time to investigate further. Will try again later though. Hopefully it wont take too much longer.

**Comment by bartkamphorst** [comment]
Any luck resolving the issue with rubygems @nricciar?

**Comment by bartkamphorst** [comment]
@nricciar Would you mind giving it another try to release 0.8.3 on rubygems? Would be much appreciated!
